--liquibase formatted sql
--changeset nvoxland:1
CREATE TABLE department
(
    id               bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    full_name        varchar(255),
    short_name       varchar(50),
    telephone_number varchar(255)
);
-- rollback drop table department;

--changeset nvoxland:2
insert into department (id, full_name, short_name, telephone_number)
values (1, 'Develop', 'Dev', '666');

--changeset nvoxland:3
CREATE TABLE person
(
    id            bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    person_id     bigint,
    lastname      varchar(255),
    name          varchar(255),
    patronymic    varchar(255),
    birthday      date,
    version_id    bigint,
    date_created  timestamp,
    active        boolean,
    department_id bigint REFERENCES department (id)
);
--rollback drop table person;

--changeset nvoxland:4
insert into person(id, person_id, lastname, name, patronymic, birthday, version_id,
                   date_created, active, department_id)
values (1, 1, 'Ivanov', 'Ivan', 'Ivanovich', '2001-01-01', 0, '2001-01-01',
        true, 1);

